/*1. Create a program with a variable named auto and try to compile it. Explain the error
message generated by the compiler.*/
#include<stdio.h>
void main()
{
  int auto;
}
// it shows error because of auto is keyword.
