/*2. Create a program with a variable named const and try to compile it. Explain the error
message generated by the compiler. */
#include<stdio.h>
void main()
{
  int const;
}
// it shows error because of const is keyword.keyword is not used in variable .
