/*.
4. Create a program with a variable named int and try to compile it. Explain the error
message generated by the compiler.*/
#include<stdio.h>
void main()
{
  float int;
}
// it shows error because of int is keyword.keyword is not used in variable .
