/*5. Create a program with a variable named break and try to compile it. Explain the error
message generated by the compiler.*/
#include<stdio.h>
void main()
{
  int break;
}
// it shows error because of break is keyword.keyword is not used in variable .
