/*
7. Create a program with a variable named char and try to compile it. Explain the error
message generated by the compiler.*/
#include<stdio.h>
void main()
{
  int continue;
}
// it shows error because of continue is keyword.keyword is not used in variable .
