/*
8. Create a program with a variable named while and try to compile it. Explain the error
message generated by the compiler.*/
#include<stdio.h>
void main()
{
  int while;
}
// it shows error because of int is keyword.keyword is not used in variable .
